### ISSUE TITLE
No sound through Docker-run endpoint

### ISSUE THREAD

**Issue by rogersmj** [noelhibbard/sharport-sync-docker#1]
Hi @noelhibbard , I found this repo through old discussions over at Mike Brady's github. I am trying to get multiple sound cards going on a RaspBerry Pi for multiple AirPlay 2 "zones".

I've followed your README but am not getting any audio. Running just one instance for now (I have instance 2 commented out in the docker file), the container starts up correctly -- it gets an IP, Shairport is running, and I can see it on my iOS devices as an AirPlay target using the name I specified in the shairport config file. I can select it as the AirPlay target, and the display on my iPhone shows that it's playing, but no sound is heard.

Here is my `/etc/pulse/system.pa` file, with the device name being the ALSA device that I previous had a "normal" (non-Docker) Shairport-Sync installation using successfully:

```
load-module module-native-protocol-unix
load-module module-alsa-sink device=hw:Headphones sink_name=FirstFloor
```
PulseAudio appears to start OK when I use that config. But like I said, I get no audio from AirPlay.

I've also tried it like this, with the device name taken from the output of `pactl list sinks short`:
```
load-module module-native-protocol-unix
load-module module-alsa-sink device=alsa_output.platform-bcm2835_audio.analog-stereo sink_name=FirstFloor
```
But when I use that configuration, I get this message in the service log for Pulseaudio:
```
ov 22 18:50:48 shairportsync pulseaudio[3202]: Failed to load module "module-alsa-sink" (argument: "device=alsa_output.platform-bcm2835_audio.analog-stereo sink_name=FirstFloor"): initialization failed
```

The shairport instance config file looks like this:

```
general = {
    name = "Main Floor";
    //      volume_range_db = 60 ; // use this advanced setting to set the range, in dB, you want between the maximum volume and the minimum volume. Range is$
    //      volume_max_db = 0.0 ; // use this advanced setting, which must have a decimal point in it, to set the maximum volume, in dB, you wish to use.
};

pa = {
    sink = "FirstFloor"; // Set this to override the default pulseaudio sink that should be used. (Untested)
};
```
(I also have some MQTT/metadata configurations in there but omitted them here.)

Listing the sinks:

```
pi@shairportsync:~/sps-docker $ pactl list sinks short
0	alsa_output.platform-bcm2835_audio.digital-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
1	alsa_output.platform-bcm2835_audio.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
2	alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
```

Running a test from outside the container, I hear sound. This works:
`paplay --verbose --device=alsa_output.platform-bcm2835_audio.analog-stereo test.wav`

There are no errors in the container's log.

I am not super familiar with Docker so I'm not sure how to run any tests from inside the container.

Since I'm not getting any errors in PulseAudio or ShairPort-Sync, I'm kind of at a loss here and would really appreciate your help.

**Comment by rogersmj** [comment]
I'm not sure if this is relevant, but I was looking at the help for `paplay` and it says it can take a sink as a device value, so I tried targeting it at the sink I created in the service config file. It doesn't play the audio file and generates an error:

```
pi@shairportsync:~/sps-docker $ paplay --verbose --device=FirstFloor test.wav
Opening a playback stream with sample specification 's16le 2ch 44100Hz' and channel map 'front-left,front-right'.
Connection established.
Stream error: No such entity
```

**Comment by noelhibbard** [comment]
You can get to the console of your container like this:
```docker exec -it <CONTAINER_NAME> sh```

Once you are in the container you can run paplay there. I'm curious what you get from ```pactl list sinks``` from within the container and if paplay works in the container.

**Comment by rogersmj** [comment]
Thanks, got into the container (weird I couldn't load the console from Portainer).

```
/ # pactl list sinks short
0	FirstFloor	module-alsa-sink.c	s16le 2ch 44100Hz	IDLE
1	Backyard	module-alsa-sink.c	s16le 2ch 44100Hz	IDLE
```

`paplay --verbose --device=FirstFloor test.wav` from inside the container...worked! So it has to be something to do with ShairPort Sync configuration.

**Comment by noelhibbard** [comment]
Stupid question but did you set ```general.output_backend = "pa"```? Also, what is the console output from shairport-sync?

You can monitor the console output by running (from the folder that contains your docker-compose.yml):
```docker-compose logs -f```

**Comment by rogersmj** [comment]
> Stupid question but did you set general.output_backend = "pa"

Not a stupid question...stupid me for not setting it! I had never set it before (because I see now the default was "alsa", which is what I was using before) and I just totally overlooked that.

It's working now. Thank you so much for your quick help. Off to get instance 2 running.

**Comment by noelhibbard** [comment]
I've made the same mistake several times. Hahaha.
